import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderTop from '@/components/HeaderTop'
import CategoryTop from '@/components/CategoryTop'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hotels&Co',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <CategoryTop />
        {children}
        
      </body>
    </html>
  )
}
